import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer'


export const metadata: Metadata = {
  title: 'Rosemond Films',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`dark:bg-slate-925 mx-auto scrollbar`}>
        <Navbar />
        
        {children}

        <Footer/>
      </body>
    </html>
  )
}
