import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Rosemond Films',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`dark:bg-slate-925 text-slate-300 mx-auto`}>
        <Navbar />
        
        {children}
      </body>
    </html>
  )
}
